### PR TITLE
Pedometer

### PR DESCRIPTION
**Pull request by harry48225**
I've added a step count display. I've tried to make the display as sympathetic to the original design as possible. I've also made whether it's shown as a configurable option. The step count also automatically remains vertically centred regardless of the magnitude of the number of steps.
basalt-steps
chalk-steps

### CODE REVIEW

**Comment by harry48225** [comment]
I've noticed that the step count doesn't recentre unless the watch face is reloaded (when the animation plays) to trigger this you have to go into a different app / just the menu. This isn't great. I think an easy way to fix this would be just to recreate the text layer every step count update however this might not be the best in terms of power consumption. Do you have any better ideas?

**Comment by C-D-Lewis** [comment]
Looks good. Could you use `text_layer_get_layer` and `layer_set_frame` to update the position?

**Comment by harry48225** [comment]
Thanks that seems to have fixed it.

**Review by C-D-Lewis — APPROVED** [review]

**Comment by harry48225** [comment]
Thanks for reviewing by pull request :). Is there anything else you need to me to do/change in order to get it merged? I see you've approved it but I can't merge it myself as I don't have write access to this repo.

**Comment by harry48225** [comment]
Hi just a bump on this @C-D-Lewis

**Pull request merged**
